name: Uptime CI
on:
  schedule:
    - cron: "0 * * * *"   # jede Stunde (GitHub Free: max 2000 min/Monat)
  workflow_dispatch:       # manuell auslösbar

jobs:
  uptime:
    name: Check services
    runs-on: ubuntu-latest
    steps:
      - name: Upptime uptime monitor
        uses: upptime/uptime-monitor@v1.41.0
        with:
          UPPTIME_GH_PAT: ${{ secrets.GH_PAT }}
